### ISSUE TITLE
Error implementing `CustomDiff` on provider config

### ISSUE THREAD

**Issue by danischm** [pulumi/pulumi-go-provider#121]
### What happened?

I would like to implement `CustomDiff` on a provider config. This is some sample code:

```
type Config struct {
	Url      string `pulumi:"url"`
	Client   *xyz.Client
}

var _ = (infer.CustomDiff[*Config, *Config])((*Config)(nil))

func (*Config) Diff(ctx p.Context, id string, olds *Config, news *Config) (p.DiffResponse, error) {
	...
}
```

Where I am getting the following error:

```
panic: fatal: An assertion has failed: Target *xyz.Config must be a struct type with `pulumi:"x"` tags to direct decoding
    goroutine 84 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /Users/danischm/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.76.1/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x20?, {0x1035fac44?, 0x6?}, {0x140000fed10?, 0x12b96d0e8?, 0x104511d28?})
        /Users/danischm/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.76.1/go/common/util/contract/assert.go:35 +0xe0
    github.com/pulumi/pulumi/sdk/v3/go/common/util/mapper.(*mapper).Decode(0x140000ab3e0, 0x0?, {0x1037f2120?, 0x140000d8120?})
        /Users/danischm/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.76.1/go/common/util/mapper/mapper_decode.go:38 +0x310
    github.com/pulumi/pulumi-go-provider/infer.decodeBase(0x14000261dd0, {0x1037f2120, 0x140000d8120}, 0x0, 0x0)
        /Users/danischm/go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.12.0/infer/resource.go:865 +0x1fc
    github.com/pulumi/pulumi-go-provider/infer.decode(...)
        /Users/danischm/go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.12.0/infer/resource.go:871
    github.com/pulumi/pulumi-go-provider/infer.diff[...]({0x1039fda20, 0x14000261f20}, {{0x0, 0x0}, {0x140001f0230, 0x61}, 0x14000261dd0, 0x14000261e00, {0x104179df0, 0x0, ...}}, ...)
        /Users/danischm/go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.12.0/infer/resource.go:638 +0x6d0
    github.com/pulumi/pulumi-go-provider/infer.(*config[...]).diffConfig(0x103a01d20?, {0x1039fda20?, 0x14000261f20?}, {{0x0?, 0x0}, {0x140001f0230, 0x61}, 0x14000261dd0, 0x14000261e00, {0x104179df0, ...}})
...
```

### Expected Behavior

Being able to implement `CustomDiff` on config.

### Steps to reproduce

outlined above

### Output of `pulumi about`

```
CLI
Version      3.78.1
Go Version   go1.20.7
Go Compiler  gc

Host
OS       darwin
Version  13.4.1
Arch     arm64
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
Hey @danischm. Sorry about that. This should be fixed by https://github.com/pulumi/pulumi-go-provider/pull/120.

**Comment by marvkis** [comment]
Hi @danischm  does the fix work for you now?

I'm running in quite the same stack trace with 0.12.2:
```
panic: fatal: An assertion has failed: Target *provider.MyLovelyConfig must be a struct type with `pulumi:"x"` tags to direct decoding
    goroutine 82 [running]:
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.failfast(...)
        /Users/christian.niessner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.79.0/go/common/util/contract/failfast.go:23
    github.com/pulumi/pulumi/sdk/v3/go/common/util/contract.Assertf(0x40?, {0x100de5e98?, 0x4?}, {0x14000550db0?, 0x14902d658?, 0x1024545b8?})
        /Users/christian.niessner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.79.0/go/common/util/contract/assert.go:35 +0xe0
    github.com/pulumi/pulumi/sdk/v3/go/common/util/mapper.(*mapper).Decode(0x140000c8a80, 0x140004b8068?, {0x101088c40?, 0x140004b8068?})
        /Users/christian.niessner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.79.0/go/common/util/mapper/mapper_decode.go:38 +0x2cc
    github.com/pulumi/pulumi-go-provider/infer/internal/ende.decode(0x14000551168?, {0x101088c40, 0x140004b8068}, 0x0, 0x0)
        /Users/christian.niessner/go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.12.2/infer/internal/ende/ende.go:61 +0x320
    github.com/pulumi/pulumi-go-provider/infer/internal/ende.Decode[...](...)
        /Users/christian.niessner/go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.12.2/infer/internal/ende/ende.go:37
    github.com/pulumi/pulumi-go-provider/infer.diff[...]({0x1013dd318, 0x140004048a0}, {{0x0, 0x0}, {0x1400004a0a0, 0x45}, 0x14000404750, 0x14000404780, {0x101f037c0, 0x0, ...}}, ...)
        /Users/christian.niessner/go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.12.2/infer/resource.go:799 +0x188
    github.com/pulumi/pulumi-go-provider/infer.(*config[...]).diffConfig(0x1013e5980, {0x1013dd318, 0x140004048a0}, {{0x0, 0x0}, {0x1400004a0a0, 0x45}, 0x14000404750, 0x14000404780, {0x101f037c0, ...}})
        /Users/christian.niessner/go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.12.2/infer/configuration.go:147 +0xb4
    github.com/pulumi/pulumi-go-provider/middleware/context.Wrap.func4({0x1013dd318?, 0x14000404810?}, {{0x0, 0x0}, {0x1400004a0a0, 0x45}, 0x14000404750, 0x14000404780, {0x101f037c0, 0x0, ...}})
        /Users/christian.niessner/go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.12.2/middleware/context/context.go:38 +0xb4
    github.com/pulumi/pulumi-go-provider/middleware/cancel.Wrap.func5({0x1013dd318?, 0x140004047b0?}, {{0x0, 0x0}, {0x1400004a0a0, 0x45}, 0x14000404750, 0x14000404780, {0x101f037c0, 0x0, ...}})
        /Users/christian.niessner/go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.12.2/middleware/cancel/cancel.go:91 +0xe0
    github.com/pulumi/pulumi-go-provider.(*provider).DiffConfig(0x140003b8e10, {0x1013d52d8?, 0x14000404720}, 0x14000230700)
        /Users/christian.niessner/go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.12.2/provider.go:697 +0x2f4
...
```
Any hints?

**Comment by marvkis** [comment]
shouldn't be there a similar conditional dispatch in [configuration.diffConfig](https://github.com/pulumi/pulumi-go-provider/blob/v0.12.2/infer/configuration.go#L145) like there is in [configuration.configure](https://github.com/pulumi/pulumi-go-provider/blob/v0.12.2/infer/configuration.go#L158) 🤔

**Comment by iwahbe** [comment]
The conditional dispatch is within the `diff` method itself:
https://github.com/pulumi/pulumi-go-provider/blob/6401f30864cd951808f8cbd2f502d800500e3bbe/infer/resource.go#L795

@marvkis If this isn't working for you I'd love to see your code so I can repro. Can you open a new issue?
