### ISSUE TITLE
Cancellation panic

### ISSUE THREAD

**Issue by blampe** [pulumi/pulumi-go-provider#186]
I was trying to test some cancellation behavior, so I ctrl-C'd during an update and got this:

```
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x10581ba68]
    goroutine 27 [running]:
    github.com/pulumi/pulumi-go-provider/middleware/cancel.(*inOutCache[...]).drain(0x1070bb940?)
    	/Users/bryce/go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.14.0/middleware/cancel/cancel.go:229 +0x158
    github.com/pulumi/pulumi-go-provider/middleware/cancel.Wrap.func2({0x1070c2460, 0x14000d88720})
    	/Users/bryce/go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.14.0/middleware/cancel/cancel.go:56 +0x44
    github.com/pulumi/pulumi-go-provider.(*provider).Cancel(0x140008cc360, {0x1070b0778?, 0x14000d886f0}, 0x106e8a4e0?)
    	/Users/bryce/go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.14.0/provider.go:972 +0x8c
    github.com/pulumi/pulumi-docker/provider/v4.dockerHybridProvider.Cancel(...)
    	/Users/bryce/src/pulumi-docker/provider/hybrid.go:64
```

I'm not even sure if this a problem with go-provider, or if it's coming from a function closure around my own code.

AFAICT `provider.Main` is already performing a [GracefulStop](https://github.com/pulumi/pulumi/blob/f3e6e9a9dd9e12ae584bdc2f8f917ad4f31214f9/sdk/go/common/util/rpcutil/serve.go#L121) for us, so I don't understand what `inOutCache` is doing. Can we not simply pass through to the provider's `Cancel` implementation, if it has one?

**Comment by lukehoban** [comment]
Marking P1 due to panic. 

Also got a report of a similar callstack from a user (though don’t have any repro steps to understand what they were doing when this happened). 

![IMG_9332](https://github.com/pulumi/pulumi-go-provider/assets/223467/a509c82f-ed77-4054-b127-8ecfd1239bae)
