### ISSUE TITLE
ValueError: '' is not a valid 

### ISSUE THREAD

**Issue by dirien** [pulumi/pulumi-go-provider#204]
### What happened?

I use the Pulumi Pinecone provider with the Python SDK and get every time following error message, when defining a Pod based index.

### Example

```python
import pulumi
import pinecone_pulumi as pinecone

pinecone_index = pinecone.PineconeIndex(
    "my-index",
    name="my-index",
    spec=pinecone.PineconeSpecArgs(
        pod=pinecone.PineconePodSpecArgs(
            environment="gcp-starter",
            pod_type="starter",
            replicas=1,
        ),
    ),
    metric="cosine",
    dimension=1536,
) 
pulumi.export("output", {
    "value": pinecone_index.host,
})
```

### Output of `pulumi about`

```shell
CLI          
Version      3.111.1
Go Version   go1.22.1
Go Compiler  gc

Plugins
NAME      VERSION
pinecone  0.4.1
python    unknown

Host     
OS       darwin
Version  14.2.1
Arch     arm64

This project is written in python: executable='/opt/homebrew/bin/python3' version='3.12.2'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/dirien

Dependencies:
NAME             VERSION
click            8.1.7
cryptography     42.0.5
distlib          0.3.8
docutils         0.20.1
filelock         3.13.1
Jinja2           3.1.3
pinecone_pulumi  0.4.1
pip              24.0
Pygments         2.17.2
python-dateutil  2.9.0.post0
python-magic     0.4.27
pytz             2024.1
requests         2.31.0
setuptools       69.2.0
wheel            0.43.0

Pulumi locates its logs in /var/folders/tv/ccfx977s0f3934vn0wcm5d7c0000gn/T/ by default
warning: Failed to get information about the current stack: No current stack
```

### Additional context

This is the error message I see during the `pulumi up`

```bash
     Type                             Name                 Plan       Info
 +   pulumi:pulumi:Stack              pinecone-python-dev  create     1 error; 1 warning; 18 debugs
 +   └─ pinecone:index:PineconeIndex  my-index             create     2 debugs

Diagnostics:
  pulumi:pulumi:Stack (pinecone-python-dev):
    debug: registering resource: ty=pulumi:pulumi:Stack, name=pinecone-python-dev, custom=False, remote=False
    debug: registering resource: ty=pinecone:index:PineconeIndex, name=my-index, custom=True, remote=False
    debug: Waiting for outstanding RPCs to complete
    debug: RPCs successfully completed
    debug: Waiting for 13 outstanding tasks to complete
    debug: beginning rpc register resource
    debug: beginning rpc register resource
    debug: beginning rpc register resource outputs
    debug: resource registration prepared: ty=pulumi:pulumi:Stack, name=pinecone-python-dev
    debug: resource registration successful: ty=pulumi:pulumi:Stack, urn=urn:pulumi:dev::pinecone-python::pulumi:pulumi:Stack::pinecone-python-dev
    debug: resource registration prepared: ty=pinecone:index:PineconeIndex, name=my-index
    warning: resource plugin pinecone is expected to have version >=0.4.1, but has 0.0.1; the wrong version may be on your path, or this may be a bug in the plugin
    debug: Configuring Pinecone provider
    debug: resource registration successful: ty=pinecone:index:PineconeIndex, urn=urn:pulumi:dev::pinecone-python::pinecone:index:PineconeIndex::my-index
    debug: exception after executing rpc: Traceback (most recent call last):
      File "/opt/homebrew/lib/python3.12/site-packages/pulumi/runtime/resource.py", line 1059, in do_register
        rpc.resolve_outputs(
      File "/opt/homebrew/lib/python3.12/site-packages/pulumi/runtime/rpc.py", line 1127, in resolve_outputs
        translated_value = translate_output_properties(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.12/site-packages/pulumi/runtime/rpc.py", line 957, in translate_output_properties
        k: translate_output_properties(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.12/site-packages/pulumi/runtime/rpc.py", line 957, in translate_output_properties
        k: translate_output_properties(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.12/site-packages/pulumi/runtime/rpc.py", line 1024, in translate_output_properties
        return typ(output)
               ^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/enum.py", line 744, in __call__
        return cls.__new__(cls, value)
               ^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/enum.py", line 1158, in __new__
        raise ve_exc
    ValueError: '' is not a valid ServerlessSpecCloud
    debug: RPC failed with exception:
    debug: Traceback (most recent call last):
      File "/opt/homebrew/lib/python3.12/site-packages/pulumi/runtime/rpc_manager.py", line 71, in rpc_wrapper
        result = await rpc
                 ^^^^^^^^^
      File "/opt/homebrew/lib/python3.12/site-packages/pulumi/runtime/resource.py", line 1059, in do_register
        rpc.resolve_outputs(
      File "/opt/homebrew/lib/python3.12/site-packages/pulumi/runtime/rpc.py", line 1127, in resolve_outputs
        translated_value = translate_output_properties(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.12/site-packages/pulumi/runtime/rpc.py", line 957, in translate_output_properties
        k: translate_output_properties(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.12/site-packages/pulumi/runtime/rpc.py", line 957, in translate_output_properties
        k: translate_output_properties(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.12/site-packages/pulumi/runtime/rpc.py", line 1024, in translate_output_properties
        return typ(output)
               ^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/enum.py", line 744, in __call__
        return cls.__new__(cls, value)
               ^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/enum.py", line 1158, in __new__
        raise ve_exc
    ValueError: '' is not a valid ServerlessSpecCloud
    debug: Cancelling 2 remaining tasks.
    debug: A future resolved in an exception, raising exception.
    error: Program failed with an unhandled exception:
    Traceback (most recent call last):
      File "/opt/homebrew/bin/pulumi-language-python-exec", line 191, in <module>
        loop.run_until_complete(coro)
      File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
        return future.result()
               ^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 153, in run_in_stack
        await run_pulumi_func(run)
      File "/opt/homebrew/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 61, in run_pulumi_func
        await wait_for_rpcs()
      File "/opt/homebrew/lib/python3.12/site-packages/pulumi/runtime/stack.py", line 132, in wait_for_rpcs
        raise exception
      File "/opt/homebrew/lib/python3.12/site-packages/pulumi/output.py", line 173, in run
        is_known = await self._is_known
                   ^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.12/site-packages/pulumi/output.py", line 104, in is_value_known
        return await is_known and not contains_unknowns(await future)
               ^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.12/site-packages/pulumi/runtime/resource.py", line 1059, in do_register
        rpc.resolve_outputs(
      File "/opt/homebrew/lib/python3.12/site-packages/pulumi/runtime/rpc.py", line 1127, in resolve_outputs
        translated_value = translate_output_properties(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.12/site-packages/pulumi/runtime/rpc.py", line 957, in translate_output_properties
        k: translate_output_properties(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.12/site-packages/pulumi/runtime/rpc.py", line 957, in translate_output_properties
        k: translate_output_properties(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/lib/python3.12/site-packages/pulumi/runtime/rpc.py", line 1024, in translate_output_properties
        return typ(output)
               ^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/enum.py", line 744, in __call__
        return cls.__new__(cls, value)
               ^^^^^^^^^^^^^^^^^^^^^^^
      File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/enum.py", line 1158, in __new__
        raise ve_exc
    ValueError: '' is not a valid ServerlessSpecCloud

  pinecone:index:PineconeIndex (my-index):
    debug: Pinecone index dimension: 1536
    debug: Previewing Pinecone index creation: my-index

```

GRPC Debug:

```json
{"method":"/pulumirpc.LanguageRuntime/GetPluginInfo","request":{},"response":{},"metadata":{"kind":"language","mode":"client","runtime":"python"}}
{"method":"/pulumirpc.LanguageRuntime/GetRequiredPlugins","request":{"project":"deprecated","pwd":"/Users/dirien/Tools/repos/pulumi-pinecone/examples/python","program":".","info":{"rootDirectory":"/Users/dirien/Tools/repos/pulumi-pinecone/examples/python","programDirectory":"/Users/dirien/Tools/repos/pulumi-pinecone/examples/python","entryPoint":".","options":{}}},"response":{"plugins":[{"name":"pinecone","kind":"resource","version":"v0.4.1","server":"github://api.github.com/pinecone-io/pulumi-pinecone"}]},"metadata":{"kind":"language","mode":"client","runtime":"python"}}
{"method":"/pulumirpc.ResourceMonitor/SupportsFeature","request":{"id":"secrets"},"response":{"hasSupport":true},"metadata":{"mode":"server"}}
{"method":"/pulumirpc.ResourceMonitor/SupportsFeature","request":{"id":"outputValues"},"response":{"hasSupport":true},"metadata":{"mode":"server"}}
{"method":"/pulumirpc.ResourceMonitor/SupportsFeature","request":{"id":"aliasSpecs"},"response":{"hasSupport":true},"metadata":{"mode":"server"}}
{"method":"/pulumirpc.ResourceMonitor/SupportsFeature","request":{"id":"deletedWith"},"response":{"hasSupport":true},"metadata":{"mode":"server"}}
{"method":"/pulumirpc.ResourceMonitor/SupportsFeature","request":{"id":"transforms"},"response":{"hasSupport":true},"metadata":{"mode":"server"}}
{"method":"/pulumirpc.ResourceMonitor/SupportsFeature","request":{"id":"resourceReferences"},"response":{"hasSupport":true},"metadata":{"mode":"server"}}
{"method":"/pulumirpc.ResourceMonitor/RegisterResource","request":{"type":"pulumi:pulumi:Stack","name":"pinecone-python-dev","object":{},"acceptSecrets":true,"supportsPartialValues":true,"acceptResources":true,"sourcePosition":{"uri":"file:///opt/homebrew/lib/python3.12/site-packages/pulumi/runtime/stack.py","line":150}},"response":{"urn":"urn:pulumi:dev::pinecone-python::pulumi:pulumi:Stack::pinecone-python-dev","object":{}},"metadata":{"mode":"server"}}
{"method":"/pulumirpc.ResourceProvider/GetPluginInfo","request":{},"response":{"version":"0.0.1"},"metadata":{"kind":"resource","mode":"client","name":"pinecone"}}
{"method":"/pulumirpc.ResourceProvider/CheckConfig","request":{"urn":"urn:pulumi:dev::pinecone-python::pulumi:providers:pinecone::default_0_4_1_github_/api.github.com/pinecone-io/pulumi-pinecone","olds":{},"news":{"pluginDownloadURL":"github://api.github.com/pinecone-io/pulumi-pinecone","version":"0.4.1"}},"response":{"inputs":{"APIKey":""}},"metadata":{"kind":"resource","mode":"client","name":"pinecone"}}
{"method":"/pulumirpc.ResourceProvider/Configure","request":{"variables":{"pinecone:config:APIKey":""},"args":{"APIKey":""},"acceptSecrets":true,"acceptResources":true,"sendsOldInputs":true,"sendsOldInputsToDelete":true},"response":{"acceptSecrets":true,"supportsPreview":true,"acceptResources":true,"acceptOutputs":true},"metadata":{"kind":"resource","mode":"client","name":"pinecone"}}
{"method":"/pulumirpc.ResourceProvider/Check","request":{"urn":"urn:pulumi:dev::pinecone-python::pinecone:index:PineconeIndex::my-index","olds":{},"news":{"dimension":1536,"metric":"cosine","name":"my-index","spec":{"pod":{"environment":"gcp-starter","podType":"starter","replicas":1}}},"randomSeed":"OINjCIWgMP68YWSP5cYCvNRmiDbiEOJEZZ9AXZ8E7bU="},"response":{"inputs":{"dimension":1536,"metric":"cosine","name":"my-index","spec":{"pod":{"environment":"gcp-starter","metaDataConfig":{},"podType":"starter","pods":0,"replicas":1,"shards":0},"serverless":{"cloud":"","region":""}}}},"metadata":{"kind":"resource","mode":"client","name":"pinecone"}}
{"method":"/pulumirpc.ResourceProvider/Create","request":{"urn":"urn:pulumi:dev::pinecone-python::pinecone:index:PineconeIndex::my-index","properties":{"dimension":1536,"metric":"cosine","name":"my-index","spec":{"pod":{"environment":"gcp-starter","metaDataConfig":{},"podType":"starter","pods":0,"replicas":1,"shards":0},"serverless":{"cloud":"","region":""}}},"preview":true},"response":{"id":"my-index","properties":{"dimension":1536,"host":"04da6b54-80e4-46f7-96ec-b56ff0331ba9","metric":"cosine","name":"my-index","spec":{"pod":{"environment":"gcp-starter","metaDataConfig":{},"podType":"starter","pods":0,"replicas":1,"shards":0},"serverless":{"cloud":"","region":""}}}},"metadata":{"kind":"resource","mode":"client","name":"pinecone"}}
{"method":"/pulumirpc.ResourceMonitor/RegisterResource","request":{"type":"pinecone:index:PineconeIndex","name":"my-index","parent":"urn:pulumi:dev::pinecone-python::pulumi:pulumi:Stack::pinecone-python-dev","custom":true,"object":{"dimension":1536,"metric":"cosine","name":"my-index","spec":{"pod":{"environment":"gcp-starter","podType":"starter","replicas":1}}},"propertyDependencies":{"dimension":{},"metric":{},"name":{},"spec":{}},"version":"0.4.1","acceptSecrets":true,"supportsPartialValues":true,"acceptResources":true,"pluginDownloadURL":"github://api.github.com/pinecone-io/pulumi-pinecone","sourcePosition":{"uri":"file:///opt/homebrew/lib/python3.12/site-packages/pinecone_pulumi/pinecone_index.py","line":123}},"response":{"urn":"urn:pulumi:dev::pinecone-python::pinecone:index:PineconeIndex::my-index","id":"my-index","object":{"dimension":1536,"host":"04da6b54-80e4-46f7-96ec-b56ff0331ba9","metric":"cosine","name":"my-index","spec":{"pod":{"environment":"gcp-starter","metaDataConfig":{},"podType":"starter","pods":0,"replicas":1,"shards":0},"serverless":{"cloud":"","region":""}}}},"metadata":{"mode":"server"}}
{"method":"/pulumirpc.LanguageRuntime/Run","request":{"project":"pinecone-python","stack":"dev","pwd":"/Users/dirien/Tools/repos/pulumi-pinecone/examples/python","program":".","dryRun":true,"parallel":40,"monitorAddress":"127.0.0.1:57511","organization":"dirien","configPropertyMap":{},"info":{"rootDirectory":"/Users/dirien/Tools/repos/pulumi-pinecone/examples/python","programDirectory":"/Users/dirien/Tools/repos/pulumi-pinecone/examples/python","entryPoint":".","options":{}}},"response":{"bail":true},"metadata":{"kind":"language","mode":"client","runtime":"python"}}
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by blampe** [comment]
@dirien looking at the provider, it seems like these are actually required https://github.com/pinecone-io/pulumi-pinecone/blob/a22f0a53c4d1ebf06fbebc1f627fd89008e5f37a/provider/pkg/pinecone/index/index.go#L23-L24

> warning: resource plugin pinecone is expected to have version >=0.4.1, but has 0.0.1; the wrong version may be on your path, or this may be a bug in the plugin

Does the latest version have the same problem?

**Comment by dirien** [comment]
@blampe yes.

I use this to be sure to hit the latest binary:

```yaml
name: pinecone-python
runtime: python
plugins:
  providers:
    - name: pinecone
      path: ../../bin
```

**Comment by blampe** [comment]
@dirien if you're able to make changes to the provider, I _think_ this would work around the issue you're seeing:
```diff
 type PineconeSpec struct {
-	Serverless PineconeServerlessSpec `pulumi:"serverless,optional,omitempty"`
-	Pod        PineconePodSpec        `pulumi:"pod,optional,omitempty"`
+	Serverless *PineconeServerlessSpec `pulumi:"serverless,optional"`
+	Pod        *PineconePodSpec        `pulumi:"pod,optional"`
 }
```

**Comment by iwahbe** [comment]
@dirien, @blampe is correct. This patch will get pulumi-pinecone working again:

```patch
 provider/pkg/pinecone/index/getIndex.go | 2 +-
 provider/pkg/pinecone/index/index.go    | 8 ++++----
 2 files changed, 5 insertions(+), 5 deletions(-)

diff --git a/provider/pkg/pinecone/index/getIndex.go b/provider/pkg/pinecone/index/getIndex.go
index 55c5c70..093a267 100644
--- a/provider/pkg/pinecone/index/getIndex.go
+++ b/provider/pkg/pinecone/index/getIndex.go
@@ -40,7 +40,7 @@ func (*LookupPineconeIndex) Call(ctx p.Context, args LookupPineconeIndexArgs) (L
 			IndexMetric:    IndexMetric(resp.JSON200.Metric),
 			IndexDimension: resp.JSON200.Dimension,
 			IndexSpec: PineconeSpec{
-				Serverless: PineconeServerlessSpec{
+				Serverless: &PineconeServerlessSpec{
 					Cloud:  ServerlessSpecCloud(resp.JSON200.Spec.Serverless.Cloud),
 					Region: resp.JSON200.Spec.Serverless.Region,
 				},
diff --git a/provider/pkg/pinecone/index/index.go b/provider/pkg/pinecone/index/index.go
index 294e6cc..d26e381 100644
--- a/provider/pkg/pinecone/index/index.go
+++ b/provider/pkg/pinecone/index/index.go
@@ -45,8 +45,8 @@ type PineconePodSpec struct {
 }
 
 type PineconeSpec struct {
-	Serverless PineconeServerlessSpec `pulumi:"serverless,optional,omitempty"`
-	Pod        PineconePodSpec        `pulumi:"pod,optional,omitempty"`
+	Serverless *PineconeServerlessSpec `pulumi:"serverless,optional,omitempty"`
+	Pod        *PineconePodSpec        `pulumi:"pod,optional,omitempty"`
 }
 
 // PineconeIndexArgs describes the configuration options available for creating or managing a Pinecone index.
@@ -178,7 +178,7 @@ func (*PineconeIndex) Create(ctx p.Context, name string, args PineconeIndexArgs,
 
 	var spec client.CreateIndexRequest_Spec
 
-	if args.IndexSpec.Serverless != (PineconeServerlessSpec{}) {
+	if args.IndexSpec.Serverless != nil {
 		ctx.Logf(diag.Debug, "Creating Pinecone serverless index: %s", args.IndexName)
 		spec = client.CreateIndexRequest_Spec{
 			Serverless: &client.ServerlessSpec{
@@ -186,7 +186,7 @@ func (*PineconeIndex) Create(ctx p.Context, name string, args PineconeIndexArgs,
 				Region: args.IndexSpec.Serverless.Region,
 			},
 		}
-	} else if args.IndexSpec.Pod != (PineconePodSpec{}) {
+	} else if args.IndexSpec.Pod != nil {
 		ctx.Logf(diag.Debug, "Creating Pinecone pod-based index: %s", args.IndexName)
 		spec = client.CreateIndexRequest_Spec{
 			Pod: &client.PodSpec{
```

I'll open an issue to track this footgun in the provider API. I'm closing as by-design, since this is a bug in pulumi-pinecone, but `infer` should warn (or maybe error) when provider authors have optional non-pointer types.

**Comment by dirien** [comment]
@iwahbe: That helped! Many thanks!
