### ISSUE TITLE
cancellation panic

### ISSUE THREAD

**Issue by blampe** [pulumi/pulumi-go-provider#224]
### What happened?

I'm still seeing a panic with v0.15.0 when I cancel updates, traceback below.

### Example

```
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xeafd92]
    goroutine 221193 [running]:
    github.com/pulumi/pulumi-go-provider/middleware/context.Wrap.func2({0x39a6ae0?, 0xc0012c3ad0?})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.15.0/middleware/context/context.go:32 +0x32
    github.com/pulumi/pulumi-go-provider/middleware/cancel.Wrap.func3({0x39a6ae0, 0xc0012c3ad0})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.15.0/middleware/cancel/cancel.go:65 +0x5a
    github.com/pulumi/pulumi-go-provider.(*provider).Cancel(0xc000f58120, {0x3995758?, 0xc0012c3aa0}, 0x0?)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi-go-provider@v0.15.0/provider.go:975 +0x85
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Cancel_Handler.func1({0x3995758, 0xc0012c3aa0}, {0x2d9d920?, 0xc0012c3a40})
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.113.0/proto/go/provider_grpc.pb.go:683 +0x72
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x3995758, 0xc0012c3a10}, {0x2d9d920, 0xc0012c3a40}, 0xc0013ae520, 0xc000c35488)
    	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3d0
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Cancel_Handler({0x3076f20?, 0xc000eb9fc0}, {0x3995758, 0xc0012c3a10}, 0xc000dd0880, 0xc000eb5b40)
    	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.113.0/proto/go/provider_grpc.pb.go:685 +0x135
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc000ebe800, {0x3995758, 0xc0012c3980}, {0x39aa4a0, 0xc000602680}, 0xc00140e900, 0xc000f2eb10, 0x544bd98, 0x0)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1386 +0xe23
    google.golang.org/grpc.(*Server).handleStream(0xc000ebe800, {0x39aa4a0, 0xc000602680}, 0xc00140e900)
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1797 +0x100c
    google.golang.org/grpc.(*Server).serveStreams.func2.1()
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1027 +0x8b
    created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 84
    	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.62.1/server.go:1038 +0x135
    error: update failed
```

### Output of `pulumi about`

CLI
Version      3.113.0
Go Version   go1.22.2
Go Compiler  gc

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by iwahbe** [comment]
I see the problem. It's pretty obvious from the stack trace.

Note: this is unrelated to https://github.com/pulumi/pulumi-go-provider/issues/186. It's a different panic in a different middleware layer.
